name: Update Featured Projects

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [main]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get latest repos
        uses: octokit/request-action@v2.x
        id: get_latest_repos
        with:
          route: GET /users/AdityaDwiNugroho/repos
          owner: AdityaDwiNugroho
          sort: created
          direction: desc
          per_page: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get most starred repos
        uses: octokit/request-action@v2.x
        id: get_starred_repos
        with:
          route: GET /users/AdityaDwiNugroho/repos
          owner: AdityaDwiNugroho
          sort: stars
          direction: desc
          per_page: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README
        run: |
          latest_repos=$(echo '${{ steps.get_latest_repos.outputs.data }}' | jq -r '.[] | "\(.name)|\(.html_url)"')
          starred_repos=$(echo '${{ steps.get_starred_repos.outputs.data }}' | jq -r '.[] | "\(.name)|\(.html_url)"')

          all_repos=$(echo -e "${latest_repos}\n${starred_repos}" | sort | uniq | head -n 2)

          readme_content=""
          while IFS='|' read -r name url; do
            readme_content="${readme_content}[![Repo Card](https://github-readme-stats.vercel.app/api/pin/?username=AdityaDwiNugroho&repo=${name}&theme=radical)](${url})\n"
          done <<< "$all_repos"

          sed -i "/<!-- FEATURED-PROJECTS:START -->/,/<!-- FEATURED-PROJECTS:END -->/c\<!-- FEATURED-PROJECTS:START -->\n${readme_content}<!-- FEATURED-PROJECTS:END -->" README.md

      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update featured projects" && git push)
